name: Build Docker Image for GHCR
on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: ghcr.io
        description: 'The image repository, defaults to ghcr.io'
      build-args:
        required: false
        type: string
        description: 'A multiline list of build-args'
      push:
        required: false
        type: boolean
        default: true
        description: 'Push image to GHCR, defaults to true'
      file:
        required: false
        type: string
        default: 'Dockerfile'
        description: 'The Dockerfile to use for builds, defaults to Dockerfile'
      tags:
        required: true
        type: string
        description: 'The image tag'
      environment:
        required: false
        default: ''
        description: 'The GitHub Environment containing the secret variable DOCKER_SECRETS'
        type: string
      ref:
        required: false
        default: ''
        description: 'The specific commitId, Tag, or Branch to checkout'
        type: string

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Build Docker Image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Log into GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          driver-opts: image=moby/buildkit:v0.10.6

      - name: Build and Push Image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          build-args: |
            ${{ inputs.build-args }}
          file: ${{ inputs.file }}
          secrets: |
            ${{ secrets.DOCKER_SECRETS }}
          push: true
          tags: ${{ inputs.tags }}